src/MoonFresh/Areas/Admin/ViewModels/Gallery/GalleryAddViewModel.cs
using DbsNetCore.Inrefaces;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace MoonFresh.Areas.Admin.ViewModels.Gallery
{
    public class GalleryAddViewModel:IViewModelImage,IViewModel
    {
        [Display(Name="Категория галлереи")]
        public string CategoryId { get; set; }
        [Display(Name = "Изображение")]
        public string PathToImage { get; set; }
        [Display(Name = "Изображение")]
        public IFormFile Image { get; set; }
        [Display(Name = "Описание")]
        public string Alt { get; set; }
        [Display(Name = "Опубликовано")]
        public bool IsActive { get; set; }
    }
}

src/MoonFresh/Areas/Admin/ViewModels/Gallery/GalleryCategoryAddViewModel.cs
using DbsNetCore.Inrefaces;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace MoonFresh.Areas.Admin.ViewModels.Gallery
{
  public class GalleryCategoryAddViewModel :IViewModel,IViewModelImage
    {
        [Required]
        [Display(Name="Название категории")]
        public string Title { get; set; }
        
        [Required]
        [Display(Name ="Изображение")]
        public IFormFile Image { get; set; }
        public string PathToImage { get; set; }

        [Display(Name ="Вкл./Откл.")]
        public bool IsActive { get; set; }
    }
}

src/MoonFresh/Areas/Admin/ViewModels/Gallery/GalleryCategoryEditViewModel.cs
using DbsNetCore.Inrefaces;
using Microsoft.AspNetCore.Http;
using MongoDB.Bson;
using MoonFresh.Areas.Admin.ViewModels;
using System.ComponentModel.DataAnnotations;

namespace MoonFresh.Areas.Admin.ViewModels.Gallery
{
    public class GalleryCategoryEditViewModel:GalleryCategoryAddViewModel,IViewModelImage,IViewModel
    {
        [Display(Name ="Старое изображение")]
        new public string PathToImage { get; set; }
        [Display(Name = "Изображение")]
        new public IFormFile Image { get; set; }
        public string  Id { get; set; }

    }
}

src/MoonFresh/Areas/Admin/ViewModels/Gallery/GalleryEditViewModel.cs
using DbsNetCore.Inrefaces;
using Microsoft.AspNetCore.Http;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MoonFresh.Areas.Admin.ViewModels.Gallery
{
    public class GalleryEditViewModel: GalleryAddViewModel,IViewModelImage, IViewModel
    {
        [Display(Name = "Старое изображение")]
        new public string PathToImage { get; set; }
        [Display(Name = "Изображение")]
        new public IFormFile Image { get; set; }

        public string Id { get; set; }
    }
}

src/MoonFresh/Areas/Admin/ViewModels/Gallery/GalleryIndexViewModel.cs
using DbsNetCore.Utils.Helpers.Models;
using System.Collections.Generic;

namespace MoonFresh.Areas.Admin.ViewModels.Gallery
{
    public class GalleryIndexViewModel
    {
       public  PageInfo PageInfo { get; set; }
        public IList<Models.Gallery> Galleres { get; set; }
        public IList<Models.GalleryCategory> GalleryCategories { get; set; }

    }
}

src/MoonFresh/Models/Gallery.cs
using DbsNetCore.Interfaces;
using DbsNetCore.Models;
using MongoDB.Bson;

namespace MoonFresh.Models
{
    public class Gallery :BaseModel,IModel,IModelWithImage
    {
        public ObjectId CategoryId { get; set; }
        public string PathToImage { get; set; }
        public string Alt { get; set; }
    }
}

src/MoonFresh/ViewModels/Home/GalleryViewModel.cs
using MoonFresh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MoonFresh.ViewModels.Home
{
    public class GalleryViewModel
    {
        public GalleryCategory Category { get; set; }
        public IEnumerable<Gallery> Gallerys { get; set; }
    }
}

src/MoonFresh/Areas/Admin/Controllers/GalleryController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MoonFresh.Models;
using MongoDB.Bson;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using MoonFresh.Areas.Admin.ViewModels.Gallery;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MoonFresh.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class GalleryController : Controller
    {
        public readonly    IRepository _db;
        private const int _take = 40;
        private Core.Areas.Admin.GalleryCRUD _gallery;
        private List<GalleryCategory> _categories;

        public GalleryController(IRepository reposytory)
        {
            _gallery = new Core.Areas.Admin.GalleryCRUD(reposytory, "img/gallery/",reposytory.GalleryCategoryes,40);
            var cat = _gallery.GetAll().Result;
            _categories = cat.Select(x => (GalleryCategory)x).ToList();
            _categories.Add(new GalleryCategory
            {
                Id = new ObjectId("000000000000000000000000"),
                Title = "Все"

            });
          
            
        }

        // GET: /<controller>/
        [HttpGet]
        public async Task<IActionResult> Index(int pageNumber=1,string categoryId= "000000000000000000000000")
        {
            
            
            ObjectId id = new ObjectId();
            if (string.IsNullOrEmpty(categoryId))
                id = new ObjectId("000000000000000000000000");
            else
            {
                id = new ObjectId(categoryId);
            }
            ViewBag.categoryId = GetCategories(id);
            var model = await _gallery.GetAllImages(id, pageNumber);
            
            return View(model);
        }

        [HttpGet]
        public IActionResult AddGalleryCategory()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddGalleryCategory(GalleryCategoryAddViewModel gcavm)
        { 
            if(!ModelState.IsValid )
            {
                return View(gcavm);
            }

          var result=  await _gallery.AddWithImage(gcavm);
            if (result == false)
                return BadRequest();

            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> EditGalleryCategory(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();
                var model =await  _gallery.Get(new ObjectId(id), new GalleryCategoryEditViewModel());
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditGalleryCategory(GalleryCategoryEditViewModel gcevm)
        {
            if (ModelState.IsValid)
            {
                await _gallery.EditWithImage(gcevm);
            }

            return RedirectToAction("Index");

        }

        [HttpPost]
        public IActionResult DeleteGalleryCategory(string id)
        {
            if (!string.IsNullOrEmpty(id))
            { var res = _gallery.DeleteWithSub(new ObjectId(id)).Result; }
            return StatusCode(200);
        }

        [HttpGet]
        public IActionResult AddGallery()
        {
            SelectList si = new SelectList(_categories, "Id", "Title");
            ViewBag.CategoryId = si;
            return View();
        }

        [HttpPost]
        public async  Task<IActionResult> AddGallery(GalleryAddViewModel gavm)
        {
            if(!ModelState.IsValid)
            {
                return View(gavm);
            }
            await _gallery.GalleryAdd(gavm);
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> EditGallery(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();
            
            var gallery = await _gallery.GetGallery(new ObjectId(id));
            ViewBag.CategoryId = GetCategories(new ObjectId(gallery.CategoryId));
            return View(gallery);

        }
        [HttpPost]
        public async Task<IActionResult> EditGallery(GalleryEditViewModel gevm)
        {
            if (!ModelState.IsValid)
                return View(gevm);
            await _gallery.EditGallery(gevm);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            if(string.IsNullOrEmpty(id))
            {
                return BadRequest();
            }
            var res=_gallery.DeleteGallery(new ObjectId(id)).Result;
            return StatusCode(200);
        }


        protected IList<SelectListItem> GetCategories(ObjectId id = new ObjectId())
        {


            List<SelectListItem> lsli = new List<SelectListItem>();
            foreach (var v in _categories)
            {
                bool selected = false;
                if (v.Id == id && id.Pid != 0)
                    selected = true;
                lsli.Add(new SelectListItem() { Text = v.Title, Value = v.Id.ToString(), Selected = selected });
            }

            return lsli;


        }

    }
}

src/MoonFresh/Areas/Admin/Controllers/MaterialController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MoonFresh.Core.Areas.Admin;
using MoonFresh.Models;
using MongoDB.Bson;
using MoonFresh.Areas.Admin.ViewModels.Material;
using DbsNetCore.Interfaces;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MoonFresh.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MaterialController :BaseController
    {
        // GET: /<controller>/
       
        MaterialCRUD _mcrud;
        MaterialCategoyCRUD _mccrud;
        List<MaterialCategory> _categories;
        public MaterialController(IRepository repo)
        {

            _mccrud = new MaterialCategoyCRUD(repo, "", repo.MaterialCategoryes, 40);
            _mcrud=new MaterialCRUD(repo, "img/materials/", repo.Materials, 40);
            _categories = _mccrud.GetAll().Result.Select(x=>(MaterialCategory)x).ToList();
            _categories.Add(new MaterialCategory
            {
                Id = new ObjectId("000000000000000000000000"),
                Title = "Все"

            });
        }
        public async Task<IActionResult> Index(int pageNumber = 1, string categoryId = "000000000000000000000000")
        {
            ObjectId id = new ObjectId();
            if (string.IsNullOrEmpty(categoryId))
                id = new ObjectId("000000000000000000000000");
            else
            {
                id = new ObjectId(categoryId);
            }
            ViewBag.categoryId = GetCategories(_categories.Select(x=>(IModelTitle)x).ToList(), id);
            var model = await _mcrud.GetAll(id, pageNumber);

            
            return View(model);
        }

        [HttpGet]
        public IActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddCategory(MaterialCategoryAddViewModel mcivm)
        {
            if(!ModelState.IsValid)
            {
                return View(mcivm);
            }
            await _mccrud.Add(mcivm);
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> EditCategory(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();
            var model = await _mccrud.Get(new ObjectId(id), new MaterialCategoryEditViewModel());
            if (model == null)
                return NotFound();
            return View((MaterialCategoryEditViewModel)model);

        }
        [HttpPost]
        public async Task<IActionResult> EditCategory(MaterialCategoryEditViewModel mcevm)
        {
            if (!ModelState.IsValid)
                return View(mcevm);
            await _mccrud.Edit(mcevm);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCategory(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();
            await _mccrud.DeleteWithSub(new ObjectId(id));
            return StatusCode(200);
        }


        [HttpGet]
        public override IActionResult Add()
        {
            ViewBag.CategoryId = GetCategories(_categories.Select(x => (IModelTitle)x).ToList());
            return base.Add();
        }

        [HttpPost]
        public async Task<IActionResult> Add(MaterialAddViewModel mavm)
        {
           
          

            return await  base.Add(mavm, ( async ()=>
            {
                return await _mcrud.AddWithImage(mavm);
                
            }));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
          
            return await base.Edit(id, async () =>
             {
                 ViewBag.CategoryId = GetCategories(_categories.Select(x => (IModelTitle)x).ToList(), new ObjectId(id));
                 return await _mcrud.Get(new ObjectId(id), new MaterialEditViewModel());
             });
        } 

        [HttpPost]
        public async Task<IActionResult>Edit(MaterialEditViewModel mevm)
        {
            return await base.Edit(mevm, async () =>
             {
                 await _mcrud.EditWithImage(mevm);
                 return true;
             });
        }

        
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            int i = 0;

            return await base.Delete(id, async () =>
             {
                 await _mcrud.DeleteWithSub(new ObjectId(id));
             });
        }

    }
}

src/MoonFresh/Areas/Admin/Views/Gallery/AddGallery.cshtml
@model MoonFresh.Areas.Admin.ViewModels.Gallery.GalleryAddViewModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Добавление галлереи";
}

<h1>Добавление материала</h1>
<hr />

@using (Html.BeginForm("AddGallery", "Gallery", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{

    <div class="row">
        <div Class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(x => x.CategoryId, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.CategoryId, "")
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Alt, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Alt, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Alt, "")
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(x => x.Image, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Image, new { htmlAttributes = new { @type = "file" } })
                    @Html.ValidationMessageFor(x => x.Image, "")
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.IsActive, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.IsActive)
                </div>
            </div>
            <input type="submit" value="Сохранить" class="btn btn-primary" />
        </div>

    </div>
}

src/MoonFresh/Areas/Admin/Views/Gallery/AddGalleryCategory.cshtml
@model MoonFresh.Areas.Admin.ViewModels.Gallery.GalleryCategoryAddViewModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Добавление категории галлереи";
}

<h1>Добавление материала</h1>
<hr />

@using (Html.BeginForm("AddGalleryCategory", "Gallery", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
   
    <div class="row">
        <div Class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(x => x.Title, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Title, "")
                </div>
            </div>
                
           
            <div class="form-group">
                @Html.LabelFor(x => x.Image, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Image, new { htmlAttributes = new { @type = "file" } })
                    @Html.ValidationMessageFor(x => x.Image, "")
                </div>
            </div>
           
            <div class="form-group">
                @Html.LabelFor(x => x.IsActive, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.IsActive)
                </div>
            </div>
            <input type="submit" value="Сохранить" class="btn btn-primary" />
        </div>

    </div>
}

src/MoonFresh/Areas/Admin/Views/Gallery/EditGallery.cshtml
@model MoonFresh.Areas.Admin.ViewModels.Gallery.GalleryEditViewModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Редактирование галлереи";
}

<h1>Добавление материала</h1>
<hr />

@using (Html.BeginForm("EditGallery", "Gallery", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x=>x.Id)
    @Html.HiddenFor(x=>x.PathToImage)

    <div class="row">
        <div Class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(x => x.CategoryId, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.CategoryId, "")
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Alt, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Alt, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Alt, "")
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.PathToImage, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    <img src="/ajax/readfile?id=@Model.PathToImage" hight="300" width="300" />
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Image, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Image, new { htmlAttributes = new { @type = "file" } })
                    @Html.ValidationMessageFor(x => x.Image, "")
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.IsActive, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.IsActive)
                </div>
            </div>
            <input type="submit" value="Сохранить" class="btn btn-primary" />
        </div>

    </div>
}

src/MoonFresh/Areas/Admin/Views/Gallery/EditGalleryCategory.cshtml
@model MoonFresh.Areas.Admin.ViewModels.Gallery.GalleryCategoryEditViewModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Добавление категории галлереи";
}

<h1>Добавление материала</h1>
<hr />

@using (Html.BeginForm("EditGalleryCategory", "Gallery", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x=>x.Id)
    @Html.HiddenFor(x=>x.PathToImage)

    <div class="row">
        <div Class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(x => x.Title, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Title, "")
                </div>
            </div>

            <div class="form-group">
               @Html.LabelFor(x => x.PathToImage, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    <img src="/ajax/readfile?id=@Model.PathToImage" hight="300" width="300" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Image, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Image, new { htmlAttributes = new { @type = "file" } })
                    @Html.ValidationMessageFor(x => x.Image, "")
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.IsActive, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.IsActive)
                </div>
            </div>
            <input type="submit" value="Сохранить" class="btn btn-primary" />
        </div>

    </div>
}

src/MoonFresh/Areas/Admin/Views/Gallery/Index.cshtml
@model MoonFresh.Areas.Admin.ViewModels.Gallery.GalleryIndexViewModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Галлерея";
}

<h1>Галлерея</h1>
<hr />
<h3>Категории галлереи</h3>
@Html.ActionLink("Добавить", "AddGalleryCategory", "Gallery", null, new { @class = "btn btn-success" })
<table class="table table-hover">
    <thead>
        <tr>
            <th>Категория</th>
            <th>Изображение</th>
            <th>Вкл.</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.GalleryCategories)
        {
            <tr>
                <td>@Html.DisplayFor(x => item.Title)</td>
                <td><img src="/ajax/readfile?id=@item.PathToImage" hight="300" width="300" /></td>
                <td>@Html.DisplayFor(x=>item.IsActive)</td>
                <td>@Html.ActionLink("Редактировать", "EditGalleryCategory", "Gallery", new { @id = item.Id }, new { @class = "btn btn-primary " })</td>
                <td> <button class="btn btn-danger DeleteFaq" value="@item.Id">Удалить</button></td>
                @*<td>@Html.ActionLink("Удалить", "DeleteCategory", "Material", new { @id = item.Id }, new { @class = "btn btn-Danger DeleteCategory" })</td>*@
            </tr>

        }
    </tbody>
</table>

<hr />
<h3>Изображения</h3>
<hr />
<h4>Фильтр</h4>
@using (Html.BeginForm("Index","Gallery",FormMethod.Get))
{
    <div class="form form-horizontal">
        <div class="col-md-5">
            <div class="form-group">

                @Html.DropDownList("categoryId", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-default" value="Фильтровать" />
        </div>
    </div>
}
<hr />
@Html.ActionLink("Добавить", "AddGallery", "Gallery", null, new { @class = "btn btn-success" })
<table class="table table-hover">
    <thead>
        <tr>
            <th>Описание</th>
            <th>Изображение</th>
            <th>Вкл.</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Galleres)
        {
            <tr>
                <td>@Html.DisplayFor(x => item.Alt)</td>
                <td><img src="/ajax/readfile?id=@item.PathToImage" hight="300" width="300" /></td>
                <td>@Html.DisplayFor(x=>item.IsActive)</td>
                <td>@Html.ActionLink("Редактировать", "EditGallery", "Gallery", new { @id = item.Id }, new { @class = "btn btn-primary " })</td>
                
                <td> <button class="btn btn-danger DeleteFaq1" value="@item.Id">Удалить</button></td>
                @*<td>@Html.ActionLink("Удалить", "Delete", "Gallery", new { @id = item.Id }, new { @class = "btn btn-Danger DeleteCategory" })</td>*@
            </tr>

        }
    </tbody>
</table>
@await Html.PartialAsync("Paging", Model.PageInfo)


@section Scripts{
    <script>
        $('.DeleteFaq').click(function (e) {
            e.preventDefault();
            var confirm = window.confirm('Вы действительно хотите удалить Категорию ?');
            if (confirm == true) {
                var id = $(this).val();

                console.log(id);

                $.post('@Url.Action("DeleteGalleryCategory", "Gallery", null)/?id=' + id, function (data) { alert(data); });

                //window.location.replace('@Url.Action("Index")');
                location.reload();
            }

        });

        $('.DeleteFaq1').click(function (e) {
            e.preventDefault();
            var confirm = window.confirm('Вы действительно хотите удалить изображение ?');
            if (confirm == true) {
                var id = $(this).val();

                console.log(id);

                $.post('@Url.Action("Delete", "Gallery", null)/?id=' + id, function (data) { alert(data); });

                window.location.replace('@Url.Action("Index")');
            }

        });
    </script>
}