src/MoonFresh/Areas/Admin/ViewModels/Service/ServiceAddViewModel.cs
using Microsoft.AspNetCore.Http;
using DbsNetCore.Inrefaces;
using System.ComponentModel.DataAnnotations;

namespace MoonFresh.Areas.Admin.ViewModels.Service
{
    public class ServiceAddViewModel:IViewModel,IViewModelImage
    {
        [Display(Name = "Заголовок"),Required]
        public string Title { get; set; }
        [Display(Name = "Описание"),Required]
        public string Description { get; set; }
        [Display(Name = "Подробнее"),Required]
        public string More { get; set; }
        [Display(Name = "Изображение")]
        public string PathToImage { get; set; }
        [Display(Name = "Иконка"),Required]
        public IFormFile Image { get; set; }
        [Display(Name = "Стоимость"),Required]
        public int Price { get; set; }
        [Display(Name = "Категория услуги")]
        public string CategoryId { get; set; }
        [Display(Name = "Опубликовано")]
        public bool IsActive { get; set; }

    }
}

src/MoonFresh/Areas/Admin/ViewModels/Service/ServiceCategoryAddViewModel.cs
using DbsNetCore.Inrefaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace MoonFresh.Areas.Admin.ViewModels.Service
{
    public class ServiceCategoryAddViewModel : IViewModel, IViewModelImage
    {
        [Display(Name="Заголовок категории"),Required]
        public string Title { get; set; }
        [Display(Name = "Описание"), Required]
        public string Description { get; set; }
        [Display(Name = "Иконка"), Required]
        public IFormFile Image { get; set; }
        public string PathToImage { get; set; }
        public bool IsActive { get; set; }
    }
}

src/MoonFresh/Areas/Admin/ViewModels/Service/ServiceCategoryEditViewModel.cs
using DbsNetCore.Inrefaces;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MoonFresh.Areas.Admin.ViewModels.Service
{
    public class ServiceCategoryEditViewModel:ServiceCategoryAddViewModel,IViewModel,IViewModelImage
    {
        public string Id { get; set; }
        [Display(Name = "Старая иконка")]
        public new string PathToImage { get; set; }
        [Display(Name = "Иконка")]
        public new IFormFile Image { get; set; }
    }
}

src/MoonFresh/Areas/Admin/ViewModels/Service/ServiceEditViewModel.cs
using DbsNetCore.Inrefaces;
using Microsoft.AspNetCore.Http;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MoonFresh.Areas.Admin.ViewModels.Service
{
    public class ServiceEditViewModel:ServiceAddViewModel, IViewModel, IViewModelImage
    {
        public string Id { get; set; }
        [Display(Name="Старая иконка")]
        public new string PathToImage { get; set; }
        [Display(Name = "Иконка")]
        public new IFormFile Image { get; set; }
    }
}

src/MoonFresh/Areas/Admin/ViewModels/Service/ServiceIndexViewModel.cs
using MoonFresh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MoonFresh.Areas.Admin.ViewModels.Service
{
    public class ServiceIndexViewModel
    {
        public IList<ServiceCategory> Categoryes { get; set; }
        public IList<Models.Service> Services { get; set; }

    }
}

src/MoonFresh/Models/Service.cs
using DbsNetCore.Interfaces;
using DbsNetCore.Models;
using MongoDB.Bson;

namespace MoonFresh.Models
{
    public class Service : BaseModel, IModel, IModelWithImage
    {
        public ObjectId CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string More { get; set; }
        public int Price { get; set; }
        public string PathToImage { get; set; }
    }
}

src/MoonFresh/Areas/Admin/Controllers/MaterialController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MoonFresh.Core.Areas.Admin;
using MoonFresh.Models;
using MongoDB.Bson;
using MoonFresh.Areas.Admin.ViewModels.Material;
using DbsNetCore.Interfaces;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MoonFresh.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MaterialController :BaseController
    {
        // GET: /<controller>/
       
        MaterialCRUD _mcrud;
        MaterialCategoyCRUD _mccrud;
        List<MaterialCategory> _categories;
        public MaterialController(IRepository repo)
        {

            _mccrud = new MaterialCategoyCRUD(repo, "", repo.MaterialCategoryes, 40);
            _mcrud=new MaterialCRUD(repo, "img/materials/", repo.Materials, 40);
            _categories = _mccrud.GetAll().Result.Select(x=>(MaterialCategory)x).ToList();
            _categories.Add(new MaterialCategory
            {
                Id = new ObjectId("000000000000000000000000"),
                Title = "Все"

            });
        }
        public async Task<IActionResult> Index(int pageNumber = 1, string categoryId = "000000000000000000000000")
        {
            ObjectId id = new ObjectId();
            if (string.IsNullOrEmpty(categoryId))
                id = new ObjectId("000000000000000000000000");
            else
            {
                id = new ObjectId(categoryId);
            }
            ViewBag.categoryId = GetCategories(_categories.Select(x=>(IModelTitle)x).ToList(), id);
            var model = await _mcrud.GetAll(id, pageNumber);

            
            return View(model);
        }

        [HttpGet]
        public IActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddCategory(MaterialCategoryAddViewModel mcivm)
        {
            if(!ModelState.IsValid)
            {
                return View(mcivm);
            }
            await _mccrud.Add(mcivm);
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> EditCategory(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();
            var model = await _mccrud.Get(new ObjectId(id), new MaterialCategoryEditViewModel());
            if (model == null)
                return NotFound();
            return View((MaterialCategoryEditViewModel)model);

        }
        [HttpPost]
        public async Task<IActionResult> EditCategory(MaterialCategoryEditViewModel mcevm)
        {
            if (!ModelState.IsValid)
                return View(mcevm);
            await _mccrud.Edit(mcevm);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCategory(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();
            await _mccrud.DeleteWithSub(new ObjectId(id));
            return StatusCode(200);
        }


        [HttpGet]
        public override IActionResult Add()
        {
            ViewBag.CategoryId = GetCategories(_categories.Select(x => (IModelTitle)x).ToList());
            return base.Add();
        }

        [HttpPost]
        public async Task<IActionResult> Add(MaterialAddViewModel mavm)
        {
           
          

            return await  base.Add(mavm, ( async ()=>
            {
                return await _mcrud.AddWithImage(mavm);
                
            }));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
          
            return await base.Edit(id, async () =>
             {
                 ViewBag.CategoryId = GetCategories(_categories.Select(x => (IModelTitle)x).ToList(), new ObjectId(id));
                 return await _mcrud.Get(new ObjectId(id), new MaterialEditViewModel());
             });
        } 

        [HttpPost]
        public async Task<IActionResult>Edit(MaterialEditViewModel mevm)
        {
            return await base.Edit(mevm, async () =>
             {
                 await _mcrud.EditWithImage(mevm);
                 return true;
             });
        }

        
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            int i = 0;

            return await base.Delete(id, async () =>
             {
                 await _mcrud.DeleteWithSub(new ObjectId(id));
             });
        }

    }
}

src/MoonFresh/Areas/Admin/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MoonFresh.Core.Areas.Admin;
using MoonFresh.Areas.Admin.ViewModels.Service;
using MongoDB.Bson;
using MoonFresh.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using DbsNetCore.Interfaces;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MoonFresh.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceController : Controller
    {
        // GET: /<controller>/
        private ServiceCRUD _service;
        private ServiceCategoryCRUD _servicecategory;
       public ServiceController(IRepository repo)
        {

            _service = new ServiceCRUD(repo, "img/services", repo.Services,40);
            _servicecategory = new ServiceCategoryCRUD(repo, "img/servicescategory", repo.ServiceCategoryes, 40);
        }
        [HttpGet]
        public async  Task<IActionResult> Index()
        {
            
            var model = new ServiceIndexViewModel
            {
                Categoryes = (await _servicecategory.GetAll()).Select(x => (ServiceCategory)x).ToList(),
                Services = (await _service.GetAll()).Select(x => (Service)x).ToList()
            };


            return View(model);
        }

        [HttpGet]
        public IActionResult AddService()
        {
            ViewBag.CategoryId = GetCategories(_servicecategory.GetAll().Result.Select(x => (IModelTitle)x).ToList());
            return View();
        }
        [HttpGet]
        public IActionResult AddServiceCategory()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddServiceCategory(ServiceCategoryAddViewModel scavm)
        {
            if (ModelState.IsValid)
            {
                await _servicecategory.AddWithImage(scavm);
                return RedirectToAction("Index");
            }
            return View(scavm);
        }
        [HttpGet]
        public async Task<IActionResult> EditServiceCategory(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();
            var model = await _servicecategory.Get(new ObjectId(id));
            if (model == null)
                return NotFound();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditServiceCategory(ServiceCategoryEditViewModel scevm)
        {
            if(ModelState.IsValid)
            {
                await _servicecategory.EditWithImage(scevm);
                return RedirectToAction("Index");
            }
            return View(scevm);
        }
        [HttpPost]
        public async Task<StatusCodeResult> DeleteServiceCategory(string id)
        {
            if(!string.IsNullOrEmpty(id))
            {
                ViewBag.CategoryId = GetCategories(_servicecategory.GetAll().Result.Select(x => (IModelTitle)x).ToList());
                await _servicecategory.DeleteWithSub(new ObjectId(id));
                return  StatusCode(200);
            }
            return StatusCode(400);
        }
        [HttpPost]
        public async Task<IActionResult> AddService(ServiceAddViewModel savm)
        {
              if(!ModelState.IsValid)
            {
                return View(savm);
            }
            await _service.AddWithImage(savm);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditService(string id)
        {

            if (string.IsNullOrEmpty(id))
            {
                return BadRequest();
            }
            ViewBag.CategoryId = GetCategories(_servicecategory.GetAll().Result.Select(x => (IModelTitle)x).ToList());
            var model =await  _service.Get(new ObjectId(id), new ServiceEditViewModel());
            if (model != null)
                return View(model);
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> EditService(ServiceEditViewModel sevm)
        {
            if (!ModelState.IsValid)
                return View(sevm);
            await _service.EditWithImage(sevm);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
                return StatusCode(400);
            await _service.DeleteWithSub(new ObjectId(id));
            return StatusCode(200);
        }


        protected virtual IList<SelectListItem> GetCategories(IList<IModelTitle> _categories, ObjectId id = new ObjectId())
        {


            List<SelectListItem> lsli = new List<SelectListItem>();
            foreach (var v in _categories)
            {
                bool selected = false;
                if (v.Id == id && id.Pid != 0)
                    selected = true;
                lsli.Add(new SelectListItem() { Text = v.Title, Value = v.Id.ToString(), Selected = selected });
            }

            return lsli;


        }

    }
}

src/MoonFresh/Areas/Admin/Views/Service/AddService.cshtml
@model MoonFresh.Areas.Admin.ViewModels.Service.ServiceAddViewModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Добавление услуги";
}

<h1>Добавление услуги</h1>
<hr />

@using (Html.BeginForm("AddService", "Service", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{

    <div class="row">
        <div Class="form-horizontal">
         
            <div class="form-group">
                @Html.LabelFor(x => x.CategoryId, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.CategoryId, "")
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Title, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Title, "")
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Description, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.TextAreaFor(x => x.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Description, "")
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.More, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.TextAreaFor(x => x.More, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.More, "")
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(x => x.Image, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Image, new { htmlAttributes = new { @type = "file" } })
                    @Html.ValidationMessageFor(x => x.Image, "")
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Price, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Price, "")
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.IsActive, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.IsActive)
                </div>
            </div>
            <input type="submit" value="Сохранить" class="btn btn-primary" />
        </div>

    </div>
}

src/MoonFresh/Areas/Admin/Views/Service/AddServiceCategory.cshtml
@model MoonFresh.Areas.Admin.ViewModels.Service.ServiceCategoryAddViewModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Добавление категории услуг";
}

<h1>@ViewBag.Title</h1>
<hr />

@using (Html.BeginForm("AddServiceCategory", "Service", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{

    <div class="row">
        <div Class="form-horizontal">

            <div class="form-group">
                @Html.LabelFor(x => x.Title, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Title, "")
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Description, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.TextAreaFor(x => x.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Description, "")
                </div>
            </div>
           
            <div class="form-group">
                @Html.LabelFor(x => x.Image, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Image, new { htmlAttributes = new { @type = "file" } })
                    @Html.ValidationMessageFor(x => x.Image, "")
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.IsActive, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.IsActive)
                </div>
            </div>
            <input type="submit" value="Сохранить" class="btn btn-primary" />
        </div>

    </div>
}

src/MoonFresh/Areas/Admin/Views/Service/EditService.cshtml
@model MoonFresh.Areas.Admin.ViewModels.Service.ServiceEditViewModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Редактирование услуги";
}

<h1>@ViewBag.Title</h1>
<hr />

@using (Html.BeginForm("EditService", "Service", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x=>x.Id)
    @Html.HiddenFor(x=>x.PathToImage)
    <div class="row">
        <div Class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(x => x.CategoryId, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.CategoryId, "")
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Title, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Title, "")
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Description, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.TextAreaFor(x => x.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Description, "")
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.More, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.TextAreaFor(x => x.More, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.More, "")
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.PathToImage, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    <img src="/ajax/readfile?id=@Model.PathToImage" hight="300" width="300" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Image, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Image, new { htmlAttributes = new { @type = "file" } })
                    @Html.ValidationMessageFor(x => x.Image, "")
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Price, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Price, "")
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.IsActive, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.IsActive)
                </div>
            </div>
            <input type="submit" value="Сохранить" class="btn btn-primary" />
        </div>

    </div>
}

src/MoonFresh/Areas/Admin/Views/Service/EditServiceCategory.cshtml
@model MoonFresh.Areas.Admin.ViewModels.Service.ServiceCategoryEditViewModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Редактирование услуги";
}

<h1>@ViewBag.Title</h1>
<hr />

@using (Html.BeginForm("EditServiceCategory", "Service", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x => x.Id)
    @Html.HiddenFor(x => x.PathToImage)
    <div class="row">
        <div Class="form-horizontal">

            <div class="form-group">
                @Html.LabelFor(x => x.Title, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Title, "")
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Description, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.TextAreaFor(x => x.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.Description, "")
                </div>
            </div>
         
            <div class="form-group">
                @Html.LabelFor(x => x.PathToImage, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    <img src="/ajax/readfile?id=@Model.PathToImage" hight="300" width="300" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Image, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.Image, new { htmlAttributes = new { @type = "file" } })
                    @Html.ValidationMessageFor(x => x.Image, "")
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.IsActive, htmlAttributes: new { @class = "control-lable col-sm-2" })
                <div class="col-sm-10">
                    @Html.EditorFor(x => x.IsActive)
                </div>
            </div>
            <input type="submit" value="Сохранить" class="btn btn-primary" />
        </div>

    </div>
}

src/MoonFresh/Areas/Admin/Views/Service/Index.cshtml
@model MoonFresh.Areas.Admin.ViewModels.Service.ServiceIndexViewModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Услуги";
}

<h1>@ViewBag.Title</h1>
<hr />
<h1>Категории услуг</h1>
@Html.ActionLink("Добавить", "AddServiceCategory", "Service", null, new { @class = "btn btn-success" })
<hr />
<table class="table table-hover">
    <thead>
        <tr>
            <th>Наименование</th>
            <th>Описание</th>
            <th>Иконка</th>
            <th>Вкл.</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Categoryes)
        {
            <tr>
                <td>@Html.DisplayFor(x => item.Title)</td>
                <td>@Html.DisplayFor(x => item.Description)</td>
                <td><img src="/ajax/readfile?id=@item.PathToImage" hight="300" width="300" /></td>
                <td>@Html.DisplayFor(x => item.IsActive)</td>
                <td>@Html.ActionLink("Редактировать", "EditServiceCategory", "Service", new { @id = item.Id }, new { @class = "btn btn-primary " })</td>
                <td> <button class="btn btn-danger DeleteFaq1" value="@item.Id">Удалить</button></td>
                @*<td>@Html.ActionLink("Удалить", "DeleteCategory", "Material", new { @id = item.Id }, new { @class = "btn btn-Danger DeleteCategory" })</td>*@
            </tr>

        }
    </tbody>
</table>


@Html.ActionLink("Добавить", "AddService", "Service", null, new { @class = "btn btn-success" })
<hr />
<table class="table table-hover">
    <thead>
        <tr>
            <th>Наименование</th>
            <th>Описание</th>
            <th>Иконка</th>
            <th>Вкл.</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Services)
        {
            <tr>
                <td>@Html.DisplayFor(x => item.Title)</td>
                <td>@Html.DisplayFor(x => item.Description)</td>
                <td><img src="/ajax/readfile?id=@item.PathToImage" hight="300" width="300" /></td>
                <td>@Html.DisplayFor(x => item.IsActive)</td>
                <td>@Html.ActionLink("Редактировать", "EditService", "Service", new { @id = item.Id }, new { @class = "btn btn-primary " })</td>
                <td> <button class="btn btn-danger DeleteFaq" value="@item.Id">Удалить</button></td>
                @*<td>@Html.ActionLink("Удалить", "DeleteCategory", "Material", new { @id = item.Id }, new { @class = "btn btn-Danger DeleteCategory" })</td>*@
            </tr>

        }
    </tbody>
</table>


@section Scripts{
    <script>
        $('.DeleteFaq').click(function (e) {
            e.preventDefault();
            var confirm = window.confirm('Вы действительно хотите удалить Категорию ?');
            if (confirm == true) {
                var id = $(this).val();

                console.log(id);

                $.post('@Url.Action("Delete", "Service", null)?id=' + id, function (data) {
                    alert(data);
                    location.reload();
                });

                //window.location.replace('@Url.Action("Index")');
                location.reload();
            }

        });

              $('.DeleteFaq1').click(function (e) {
            e.preventDefault();
            var confirm = window.confirm('Вы действительно хотите удалить Категорию ?');
            if (confirm == true) {
                var id = $(this).val();

                console.log(id);

                $.post('@Url.Action("DeleteServiceCategory", "Service", null)?id=' + id, function (data) {
                    alert(data);
                    location.reload();
                });

                //window.location.replace('@Url.Action("Index")');
                location.reload();
            }

        });


    </script>
}