src/MoonFresh/Areas/Admin/ViewModels/Property/PropertyAddViewModel.cs
using MoonFresh.Models;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using DbsNetCore.Inrefaces;
using DbsNetCore.Models;

namespace MoonFresh.Areas.Admin.ViewModels.Property
{
    public class PropertyAddViewModel:IViewModel
    {

        [Display(Name = "Наименование конфигурации")]
        public string Name { get; set; }
          
        [Required, Display(Name = "Режим работы")]
        public string TimeOfWorck { get; set; }
        [Required, Display(Name = "Телефон")]
        public IDictionary<string, string> Phone { get; set; }
       
        public string PathToLogo { get; set; }
        [Display(Name = "Логотип"),Required]
        public IFormFile Logo { get; set; }
        [Display(Name = "Изображение"), Required]
        public IFormFile Image { get; set; }
        [Display(Name = "Яндекс метрика")]
        public string Yascript { get; set; }
        [Display(Name = "Гугл аналитика")]
        public string Gscript { get; set; }
        public string KeyWords { get; set; }
        [Required, Display(Name = "Описание")]
        public string Description { get; set; }
        public MailSetting MailSetting { get; set; }
        public IList<Social> Social { get; set; }
        public About About { get; set; }
        public string Addres { get; set; }
        public string Email { get; set; }

    }
}

src/MoonFresh/Areas/Admin/ViewModels/Property/PropertyEditViewModel.cs
using MoonFresh.Models;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using DbsNetCore.Inrefaces;
using DbsNetCore.Models;

namespace MoonFresh.Areas.Admin.ViewModels.Property
{
    public class PropertyEditViewModel:PropertyAddViewModel,IViewModel
    {
        public string Id { get; set; }
        public List<Social> NewSocial { get; set; }
        public IDictionary<string, string> NewPhone { get; set; }
        [Display(Name="Старый логотоп")]
        new public string PathToLogo { get; set; }
        [Display(Name="Логотип")]
        new public  IFormFile Logo { get; set; }
        [Display(Name = "Изображение")]
        new public IFormFile Image { get; set; }
        //public PropertyEditViewModel()
        //{
        //    NewSocial = new List<MoonFresh.Models.Social>();
        //    NewPhone = new Dictionary<string, string>();
        //}
    }   
}

src/MoonFresh/Models/Property.cs
using DbsNetCore.Interfaces;
using DbsNetCore.Models;

namespace MoonFresh.Models
{
    public class Property :PropertyBase,IModel
    {
       
        public About About {get;set;}
        public string Addres { get; set; }
        public double Long { get; set; }
        public double Lat { get; set; }
        public string Email { get; set; }

        public Property():base()
        {

            About = new About();
           
        }
    }
}

src/MoonFresh/Areas/Admin/Controllers/PropertyController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MoonFresh.Models;
using MoonFresh.Areas.Admin.ViewModels.Property;
using DbsNetCore.Utils;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MoonFresh.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PropertyController :BaseController
    {
        private readonly IRepository _repository;
        private const string _Url = "/admin/Testimonial/";
        private const string _PathToImage = "img/Social/";

        public PropertyController(IRepository repository)
        {
            _repository = repository;


        }

        // GET: /<controller>/
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var property = await _repository.Propertys.GetOne(x => x.Name == "Шаблон", cacheName:"Шаблон");

            return View(property);
        }

       

        [HttpPost]
        public async Task<IActionResult> Add(PropertyAddViewModel pavm)
        {

            return await base.Add(pavm, async () =>
            {

                                                                                   

                Property property = AutoMapper<PropertyAddViewModel, Property>.Mapping(pavm, new Property());
                if (pavm.Logo != null)
                {
                    var result = _repository.Files.Upload(pavm.Logo, pavm.Logo.FileName);
                    property.PathToLogo = result.Name;
                }
                if(pavm.Image!=null)
                {
                    var result = _repository.Files.Upload(pavm.Image, pavm.Image.FileName);
                    property.About.PathToImage = result.Name;
                }

                         
                await _repository.Propertys.Save(property);
                return true;

            });
         

        }


        [HttpGet]
        public async Task<IActionResult> Edit(string name)
        {
            return await base.Edit(name, async () =>
            {
                var itm = await _repository.Propertys.GetOne(x => x.Name == name, cacheName: name);
                PropertyEditViewModel pevm = new PropertyEditViewModel();
                pevm = AutoMapper<Property, PropertyEditViewModel>.Mapping(itm, pevm);
                
                return pevm;
            });

            }


        [HttpPost]
        public async Task<IActionResult> Edit(PropertyEditViewModel pevm)
        {
            return await base.Edit(pevm, async () =>
            {
                Property property = new Property();
                property = AutoMapper<PropertyEditViewModel, Property>.Mapping(pevm, property);
                           
              
                if(pevm.NewSocial!=null)
                foreach (var itm in pevm.NewSocial)
                {
                    if (!string.IsNullOrEmpty(itm.Name))
                        property.Social.Add(itm);
                }
                if(pevm.NewPhone!=null)
                foreach(var itm in pevm.NewPhone)
                {
                    property.Phone.Add(itm);
                }
                if (pevm.Logo != null)
                {
                    _repository.Files.ReplaceFile(property.PathToLogo, pevm.Logo);
                }
                if (pevm.Image != null)
                {
                    _repository.Files.ReplaceFile(property.About.PathToImage, pevm.Image);
                }
               var geo= await Utils.GoogleGeocode(pevm.Addres);
                property.Lat = geo.results[0].geometry.location.lat;
                property.Long = geo.results[0].geometry.location.lng;
                await _repository.Propertys.Replace(x => x.Id == property.Id, property);
                return true;

            });




        }


    }
}

src/MoonFresh/Areas/Admin/Views/Property/Add.cshtml
@model MoonFresh.Areas.Admin.ViewModels.Property.PropertyAddViewModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h1>Настройки</h1>
<hr />
@using (Html.BeginForm("Add", "Property", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-sm-6">
            <h3>Настройки шаблона главной страницы</h3>
            <div class="form-horizontal">

                <div class="form-group">
                    @Html.LabelFor(x => x.Name, htmlAttributes: new { @class = "control-lable col-sm-3" })
                    <div class="col-sm-9">
                        @Html.EditorFor(x => x.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(x => x.Name, "")
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.Logo, htmlAttributes: new { @class = "control-lable col-sm-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(x => x.Logo)
                        @Html.ValidationMessageFor(x => x.Logo, "")
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.TimeOfWorck, htmlAttributes: new { @class = "control-lable col-sm-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(x => x.TimeOfWorck, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(x => x.TimeOfWorck, "")
                    </div>
                </div>
              
             <figure>
                <legend>SEO</legend>
                     
                <div class="form-group">
                    @Html.LabelFor(x => x.Yascript, htmlAttributes: new { @class = "control-lable col-sm-2" })
                    <div class="col-sm-10">
                        @Html.TextAreaFor(x => x.Yascript, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(x => x.Yascript, "")
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.Gscript, htmlAttributes: new { @class = "control-lable col-sm-2" })
                    <div class="col-sm-10">
                        @Html.TextAreaFor(x => x.Gscript, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(x => x.Gscript, "")
                    </div>
                </div>
                 <div class="form-group">
                     @Html.LabelFor(x => x.KeyWords, htmlAttributes: new { @class = "control-lable col-sm-2" })
                     <div class="col-sm-10">
                         @Html.EditorFor(x => x.KeyWords, new { htmlAttributes = new { @class = "form-control" } })
                         @Html.ValidationMessageFor(x => x.KeyWords, "")
                     </div>
                 </div>
                 <div class="form-group">
                     @Html.LabelFor(x => x.Description, htmlAttributes: new { @class = "control-lable col-sm-2" })
                     <div class="col-sm-10">
                         @Html.EditorFor(x => x.Description, new { htmlAttributes = new { @class = "form-control" } })
                         @Html.ValidationMessageFor(x => x.Description, "")
                     </div>
                 </div>

           </figure>

        </div>
      </div>
        <div class="col-sm-6">
            <h3>О компании</h3>
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(x => x.About.Title, htmlAttributes: new { @class = "control-lable col-sm-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(x => x.About.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(x => x.About.Title, "")
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.About.Description, htmlAttributes: new { @class = "control-lable col-sm-2" })
                    <div class="col-sm-10">
                        @Html.TextAreaFor(x => x.About.Description)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.About.More, htmlAttributes: new { @class = "control-lable col-sm-2" })
                    <div class="col-sm-10">
                        @Html.TextAreaFor(x => x.About.More)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.Image, htmlAttributes: new { @class = "control-lable col-sm-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(x => x.Image)
                        @Html.ValidationMessageFor(x => x.Image, "")
                    </div>
                </div>
                <figure class="figure">
                    <legend>Контакты</legend>
                    <div class="form-group">
                        @Html.LabelFor(x => x.Addres, htmlAttributes: new { @class = "control-lable col-sm-2" })
                        <div class="col-sm-10">
                            @Html.TextAreaFor(x => x.Addres)
                        </div>
                    </div>
                    <figure>
                        <div class="phones">
                            <div class="form-group">
                                <button class="btn btn-success" id="addPhone">Добавить Телефон</button>
                            </div>
                            <div class="form-group">
                                @Html.Label(null, "Описание", htmlAttributes: new { @class = "control-lable col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.Editor("Phone[0].Key", new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(x => x.Phone, "")
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label(null, "Телефон", htmlAttributes: new { @class = "control-lable col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.Editor("Phone[0].Value", new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(x => x.Phone.Single().Value, "")
                                </div>
                            </div>
                        </div>
                    </figure>
                    <hr />

                    <div class="form-group">
                        @Html.LabelFor(x => x.Email, htmlAttributes: new { @class = "control-lable col-sm-2" })
                        <div class="col-sm-10">
                            @Html.EditorFor(x => x.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(x => x.Email, "")
                        </div>
                    </div>
                </figure>
            </div>

        </div>
         
    </div>

    <fieldset>
        <legend>Социальные сети</legend>
        <button class="btn btn-success" id="add">Добавить социальную сеть</button>
        <div class="Infographics">
            <br />
            <div class="form form-inline">
                <div class="form-group">
                    <label>Наименование</label>
                    <input type="text" class="form-control" name="Social[0].Name">
                </div>
                <div class="form-group">
                    <label>Ссылка</label>
                    <input type="text" class="form-control" name="Social[0].Href">
                </div>
                <div class="form-group">
                    <label>Иконка</label>
                    <input type="text" name="Social[0].Image">
                </div>
            </div>
        </div>
    </fieldset>
    <br />
    <fieldset>
        <legend>Настройки почты</legend>
        <div class="form-group">
            @Html.LabelFor(x => x.MailSetting.mailFrom, htmlAttributes: new { @class = "control-lable col-sm-2" })
            <div class="col-sm-10">
                @Html.EditorFor(x => x.MailSetting.mailFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(x => x.MailSetting.mailFrom, "")
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.MailSetting.mailFromeName, htmlAttributes: new { @class = "control-lable col-sm-2" })
            <div class="col-sm-10">
                @Html.EditorFor(x => x.MailSetting.mailFromeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(x => x.MailSetting.mailFromeName, "")
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.MailSetting.passwd, htmlAttributes: new { @class = "control-lable col-sm-2" })
            <div class="col-sm-10">
                @Html.EditorFor(x => x.MailSetting.passwd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(x => x.MailSetting.passwd, "")
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.MailSetting.host, htmlAttributes: new { @class = "control-lable col-sm-2" })
            <div class="col-sm-10">
                @Html.EditorFor(x => x.MailSetting.host, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(x => x.MailSetting.host, "")
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.MailSetting.port, htmlAttributes: new { @class = "control-lable col-sm-2" })
            <div class="col-sm-10">
                @Html.EditorFor(x => x.MailSetting.port, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(x => x.MailSetting.port, "")
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.MailSetting.textpart, htmlAttributes: new { @class = "control-lable col-sm-2" })
            <div class="col-sm-10">
                @Html.EditorFor(x => x.MailSetting.textpart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(x => x.MailSetting.textpart, "")
            </div>
        </div>

    </fieldset>
    <br />
    <input type="submit" class="btn btn-primary" value="Добавить" />

}

@section Scripts{

    <script>
        var i = 1;
        var c = 1;
        $('#add').click(function (e) {
            e.preventDefault();
            $('.Infographics').append('<br/><div class="form form-inline"><div class="form-group"><label>Наименование</label><input type="text" class="form-control" name="Social[' + i + '].Name"></div><div class="form-group"><label>Ссылка</label><input type="text" class="form-control" name="Social[' + i + '].Href"></div><div class="form-group"><label>Иконка</label><input type="text"  name="Social[' + i + '].Image"></div></div>')
            i++;



        });
        $('#addPhone').click(function (e) {
            e.preventDefault();
            $('.phones').append('<br/><div class="form-group"><label class="control-lable col-sm-2">Описание</label><div class="col-sm-10"><input type="text" class="form-control" name="Phone[' + i + '].Key"></div></div><div class="form-group"><label class="control-lable col-sm-2">Телефон</label><div class="col-sm-10"><input type="text" class="form-control" name="Phone[' + i + '].Value"></div></div>')
            i++;



        });

        //$('#add_counter').click(function (e) {
        //    e.preventDefault();
        //    $('.Counters').append('<br/><div class="form form-horizontal"><div class="form-group"><label>Наименование</label><input type="text" class="form-control" name="Counters[' + c + '].Name"></div><div class="form-group"><label>Показатель</label><input type="text" class="form-control" name="Counters[' + c + '].Cout"></div></div><hr />')
        //    c++;



        //});
    </script>
}

src/MoonFresh/Areas/Admin/Views/Property/Index.cshtml
@model MoonFresh.Models.Property
@{
    ViewBag.Title = "Настройки";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h1>Настройки</h1>
<hr />


@Html.ActionLink("Добавить", "Add", "Property", null, new { @class = "btn btn-success" })
@if (Model != null)
{
    @Html.DisplayForModel()
}
@Html.ActionLink("Редактировать", "Edit", "Property", new { @name = Model.Name }, new { @class = "btn btn-primary" })